### ISSUE TITLE
FindColmap.cmake includes vlfeat which does not exist

### ISSUE THREAD

**Issue by sontung** [conda-forge/colmap-feedstock#13]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

As found with @Tobias-Fischer, the cmake in colmap refers to `vlfeat` but the library is actually called just `vl`. This needs fixing.

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by Tobias-Fischer** [comment]
Note that we unvendor vlfeat, sth must be wrong with the way we are doing it:

https://github.com/conda-forge/colmap-feedstock/blob/main/recipe/unvendor_libs.patch

@traversaro - sorry to bother you, but you are the cmake expert, can you see what's wrong with the approach we are taking?

**Comment by Tobias-Fischer** [comment]
Found the culprit - sorry for the noise @traversaro
